// Regenerates demo/data.js: runs the built server (dist/index.js) over stdio, makes the tool
// calls the demo page shows, and saves the trimmed replies. Run from the repo root:
//   npm run build && node demo/capture.mjs
// Set GITHUB_TOKEN to avoid GitHub's unauthenticated rate limit.
import { readFileSync, writeFileSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const CALLS = [
  ["sources", "list_sources", {}],
  ["categories", "list_categories", { source: "shadcn" }],
  ["search", "search_resources", { source: "fontsource", query: "atkinson", limit: 3 }],
  ["searchAll", "search_all", { query: "marquee", perSource: 2, limit: 8 }],
  ["resource", "get_resource", { source: "webfeatures", id: "has" }],
  ["viewTransitions", "get_resource", { source: "webfeatures", id: "view-transitions" }],
  ["code", "get_code", { source: "uiverse", id: "/Buttons/cssbuttons-io_calm-tiger-42.html" }],
  ["shadcnButton", "get_code", { source: "shadcn", id: "button" }],
  ["magicMarquee", "get_code", { source: "magicui", id: "marquee" }],
  ["aceternity", "search_resources", { source: "aceternity", query: "card", limit: 2 }],
  ["font", "get_resource", { source: "fontsource", id: "big-shoulders-display" }],
  ["palette", "get_code", { source: "radixcolors", id: "/blue-dark.css" }],
  ["tabs", "get_code", { source: "apg", id: "/content/patterns/tabs/examples/js/tabs-automatic.js" }],
  ["borrowed", "get_code", { source: "refero", id: "90ce5883-bb24-4466-93f7-801cd617b0d1", file: "tokens.json" }],
  ["gradient", "get_resource", { source: "uigradients", id: "royal-blue" }],
];

/** Shrink a reply for display: at most `max` list items, code cut to 900 characters. */
function trim(v, max = 4) {
  if (Array.isArray(v)) return v.slice(0, max).map((x) => trim(x, max));
  if (typeof v === "string") return v.length > 900 ? `${v.slice(0, 900)}\n…` : v;
  if (v && typeof v === "object") {
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, trim(x, max)]));
  }
  return v;
}

const client = new Client({ name: "demo-capture", version: "1" });
await client.connect(
  new StdioClientTransport({ command: process.execPath, args: ["dist/index.js"], env: process.env }),
);
const calls = {};
for (const [key, tool, args] of CALLS) {
  const r = await client.callTool({ name: tool, arguments: args });
  const reply = JSON.parse(r.content[0].text);
  if (r.isError) throw new Error(`${tool} failed: ${reply.error}`);
  calls[key] = {
    tool,
    args,
    reply: key === "sources" ? reply : trim(reply, key === "searchAll" ? 8 : 4),
  };
}
await client.close();

// The page renders the atlas from the full list and the tabs from the trimmed replies.
const { version } = JSON.parse(readFileSync("package.json", "utf-8"));
const data = { version, capturedAt: new Date().toISOString().slice(0, 10), calls };
writeFileSync(
  "demo/data.js",
  `// Generated by demo/capture.mjs from frontend-inspo-mcp ${version}. Do not edit by hand.\nwindow.INSPO = ${JSON.stringify(data, null, 1)};\n`,
);
console.log(`demo/data.js: ${Object.keys(calls).length} calls, ${calls.sources.reply.length} sources`);
